apiVersion: v1
kind: Secret
metadata:
  name: bpdlh-app-env
type: Opaque
stringData:
  APP_KEY: "base64:8MEnLAO+XTKz7l68ciZ+AMToEzQMOkftL2FnHfgj+vU="
  # Database Utama (bpdlh_like)
  DB_CONNECTION: "mysql"
  DB_HOST: "host.k3d.internal"
  DB_PORT: "3306"
  DB_DATABASE: "bpdlh_like"
  DB_USERNAME: "root"
  DB_PASSWORD: "root_password"
  # Database API (bpdlh_api)
  DB_HOST_API: "host.k3d.internal"
  DB_PORT_API: "3306"
  DB_DATABASE_API: "bpdlh_api"
  DB_USERNAME_API: "root"
  DB_PASSWORD_API: "root_password"
  # Database Wilayah (bpdlh_wilayah)
  DB_HOST_WILAYAH: "host.k3d.internal"
  DB_PORT_WILAYAH: "3306"
  DB_DATABASE_WILAYAH: "bpdlh_wilayah"
  DB_USERNAME_WILAYAH: "root"
  DB_PASSWORD_WILAYAH: "root_password"
