apiVersion: v1
kind: Secret
metadata:
  name: bpdlh-app-env
type: Opaque
stringData:
  APP_KEY: "base64:8MEnLAO+XTKz7l68ciZ+AMToEzQMOkftL2FnHfgj+vU="
  DB_CONNECTION: "mysql"
  DB_HOST: "host.k3d.internal"
  DB_PORT: "3306"
  DB_DATABASE: "bpdlh_like"
  DB_USERNAME: "root"
  DB_PASSWORD: "root_password"
