apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdlh-like-backend-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpdlh-like-backend-worker
  template:
    metadata:
      labels:
        app: bpdlh-like-backend-worker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: worker
          image: ghcr.io/beninfcrb/bpdlh-like-backend:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "php",
              "artisan",
              "queue:work",
              "--sleep=3",
              "--tries=3",
              "--timeout=120",
            ]
          env:
            - name: APP_ENV
              value: production
            - name: APP_DEBUG
              value: "false"
            - name: TELESCOPE_ENABLED
              value: "false"
            - name: CACHE_DRIVER
              value: "file"
            - name: SESSION_DRIVER
              value: "file"
            - name: FORCE_HTTPS
              value: "false"
          envFrom:
            - secretRef:
                name: bpdlh-app-env
